# Generated by Django 5.2.5 on 2025-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=100)),
                ('nome_real', models.CharField(max_length=100)),
                ('poder_principal', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('historia', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
