# Generated by Django 5.2.5 on 2025-09-10 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
