# Generated by Django 5.2.5 on 2025-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='email_hero',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
