# Generated by Django 5.2.5 on 2025-10-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_hero_email_contato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='email_contato',
        ),
    ]
