# Generated by Django 5.2.5 on 2025-10-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_hero_imagem'),
        ('heroes', '0003_remove_hero_email_contato'),
    ]

    operations = [
    ]
